services:
  shard:
    container_name: shard
    build:
      context: ./shard
    environment:
      SHARDER_BASE: /app/data
    restart: unless-stopped
    volumes:
    - shard-storage:/app/data
volumes:
  shard-storage: {}
