global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["server:8000"]

  - job_name: "nginx"
    metrics_path: /metrics
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "shard_nodes"
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/shard_targets.json
        refresh_interval: 5s
